# Generated by Django 5.1.6 on 2025-03-17 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(max_length=255)),
                ('ticket_no', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_year', models.CharField(max_length=255)),
                ('grade_level', models.CharField(max_length=255)),
                ('with_lrn', models.BooleanField()),
                ('returning', models.BooleanField()),
                ('transferee', models.BooleanField()),
                ('psa_no', models.CharField(max_length=255)),
                ('lrn', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('extension_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('mother_tongue', models.CharField(max_length=255)),
                ('indigenous', models.BooleanField()),
                ('indigenous_specify', models.CharField(blank=True, max_length=255, null=True)),
                ('four_ps', models.BooleanField()),
                ('four_ps_household', models.CharField(blank=True, max_length=255, null=True)),
                ('disability', models.BooleanField()),
                ('disability_type', models.CharField(blank=True, max_length=255, null=True)),
                ('current_house_no', models.CharField(max_length=255)),
                ('current_street_name', models.CharField(max_length=255)),
                ('current_barangay', models.CharField(max_length=255)),
                ('current_municipality_city', models.CharField(max_length=255)),
                ('current_province', models.CharField(max_length=255)),
                ('current_country', models.CharField(max_length=255)),
                ('current_zipcode', models.CharField(max_length=255)),
                ('same_as_current', models.BooleanField()),
                ('permanent_house_no', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_barangay', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_municipality_city', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_province', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_country', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('father_last_name', models.CharField(max_length=255)),
                ('father_first_name', models.CharField(max_length=255)),
                ('father_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_contact_number', models.CharField(max_length=255)),
                ('mother_maiden_last_name', models.CharField(max_length=255)),
                ('mother_maiden_first_name', models.CharField(max_length=255)),
                ('mother_maiden_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_maiden_contact_number', models.CharField(max_length=255)),
                ('guardian_last_name', models.CharField(max_length=255)),
                ('guardian_first_name', models.CharField(max_length=255)),
                ('guardian_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_contact_number', models.CharField(max_length=255)),
                ('last_grade_level_completed', models.CharField(blank=True, max_length=255, null=True)),
                ('last_school_year_completed', models.CharField(blank=True, max_length=255, null=True)),
                ('last_school_attended_address', models.CharField(blank=True, max_length=255, null=True)),
                ('school_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transferee_last_grade_level_completed', models.CharField(blank=True, max_length=255, null=True)),
                ('transferee_last_school_year_completed', models.CharField(blank=True, max_length=255, null=True)),
                ('transferee_last_school_attended_address', models.CharField(blank=True, max_length=255, null=True)),
                ('transferee_school_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
