# Generated by Django 5.1.6 on 2025-03-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juniorenrollment',
            old_name='ticket_no',
            new_name='application_no',
        ),
    ]
