# Generated by Django 5.1.6 on 2025-03-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_remove_juniorenrollment_current_barangay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='juniorenrollment',
            name='gen_avg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='juniorenrollment',
            name='documents_submitted',
            field=models.ManyToManyField(blank=True, to='landingpage.document'),
        ),
    ]
