# Generated by Django 5.1.6 on 2025-03-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_document_alter_juniorenrollment_gen_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juniorenrollment',
            name='gen_avg',
            field=models.IntegerField(),
        ),
    ]
