# Generated by Django 5.1.6 on 2025-03-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_alter_juniorenrollment_gen_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='juniorenrollment',
            name='early_reg',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
