# Generated by Django 5.1.6 on 2025-03-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0009_remove_document_user_document_enrollment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juniorenrollment',
            name='documents_submitted',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='juniorenrollment',
            name='documents_submitted',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
