# Generated by Django 5.1.6 on 2025-03-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0010_remove_juniorenrollment_documents_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juniorenrollment',
            name='documents_submitted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
