# Generated by Django 5.1.6 on 2025-03-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0012_applicationapproved_applicationrejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrejected',
            name='message_rejected',
            field=models.TextField(blank=True, null=True),
        ),
    ]
