# Generated by Django 5.1.6 on 2025-03-24 20:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0013_applicationrejected_message_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationrejected',
            name='message_rejected',
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literacy_level', models.CharField(max_length=255)),
                ('literacy_result', models.TextField()),
                ('numeracy_level', models.CharField(max_length=255)),
                ('numeracy_result', models.TextField()),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='landingpage.applicationapproved')),
            ],
        ),
    ]
