# Generated by Django 5.1.6 on 2025-03-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0015_applicationapproved_is_assessed_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrejected',
            name='message_rejected',
            field=models.TextField(blank=True, null=True),
        ),
    ]
