# Generated by Django 5.1.6 on 2025-03-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0017_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gen_avg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
