# Generated by Django 5.1.6 on 2025-03-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0018_student_gen_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gen_avg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='new_avg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
