# Generated by Django 5.1.6 on 2025-04-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0019_alter_student_gen_avg_alter_student_new_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationapproved',
            name='document_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicationrejected',
            name='document_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='juniorenrollment',
            name='document_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
