# Generated by Django 5.1.6 on 2025-04-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0020_applicationapproved_document_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationapproved',
            name='document_status',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='document_status',
        ),
        migrations.RemoveField(
            model_name='juniorenrollment',
            name='document_status',
        ),
    ]
