# Generated by Django 5.1.6 on 2025-04-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0022_alter_applicationapproved_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('Enrolled', 'Enrolled'), ('Transferred', 'Transferred')], default='Enrolled', max_length=50),
        ),
    ]
