# Generated by Django 5.1.6 on 2025-04-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0026_announcement_type_alter_announcement_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_active', models.BooleanField(default=False)),
                ('early_registration_active', models.BooleanField(default=False)),
                ('enrollment_start_date', models.DateField(blank=True, null=True)),
                ('enrollment_deadline_date', models.DateField(blank=True, null=True)),
                ('early_registration_start_date', models.DateField(blank=True, null=True)),
                ('early_registration_deadline_date', models.DateField(blank=True, null=True)),
                ('announcement_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
