# Generated by Django 5.1.6 on 2025-04-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0027_enrollmentmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('Enrolled', 'Enrolled'), ('Transferred', 'Transferred'), ('Dropped', 'Dropped')], default='Enrolled', max_length=50),
        ),
    ]
