# Generated by Django 5.1.6 on 2025-05-13 14:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0028_alter_student_student_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationapproved',
            name='age',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='application_no',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='documents_submitted',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='early_reg',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='enrollment_type',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='extension_name',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='gen_avg',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='lrn',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='mother_tongue',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='psa_no',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='status',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='student_type',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='user',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='applicationapproved',
            name='with_lrn',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='age',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='application_no',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='documents_submitted',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='early_reg',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='enrollment_type',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='extension_name',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='gen_avg',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='lrn',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='mother_tongue',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='psa_no',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='status',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='student_type',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='user',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='applicationrejected',
            name='with_lrn',
        ),
        migrations.CreateModel(
            name='EnrollmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(max_length=255)),
                ('application_no', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('school_year', models.CharField(max_length=255)),
                ('grade_level', models.CharField(max_length=255)),
                ('with_lrn', models.BooleanField()),
                ('student_type', models.CharField(blank=True, max_length=255, null=True)),
                ('gen_avg', models.IntegerField()),
                ('psa_no', models.CharField(max_length=255)),
                ('lrn', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('extension_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('mother_tongue', models.CharField(max_length=255)),
                ('documents_submitted', models.TextField(blank=True, null=True)),
                ('early_reg', models.BooleanField(blank=True, null=True)),
                ('enrollment_type', models.CharField(choices=[('JHS', 'Junior High School'), ('SHS', 'Senior High School')], default='JHS', max_length=3)),
                ('semester', models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester')], default='1st', max_length=3)),
                ('strand', models.CharField(choices=[('ABM', 'Accountancy, Business, and Management'), ('STEM', 'Science, Technology, Engineering, and Mathematics')], default='ABM', max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='applicationapproved',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.enrollmentform'),
        ),
        migrations.AddField(
            model_name='applicationrejected',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.enrollmentform'),
        ),
        migrations.DeleteModel(
            name='JuniorEnrollment',
        ),
    ]
