# Generated by Django 5.1.6 on 2025-05-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0029_remove_applicationapproved_age_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enrollmentform',
            table='enrollment_form',
        ),
    ]
