# Generated by Django 5.1.6 on 2025-05-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0030_alter_enrollmentform_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='announcement',
            table='announcement',
        ),
        migrations.AlterModelTable(
            name='applicationapproved',
            table='application_approved',
        ),
        migrations.AlterModelTable(
            name='applicationrejected',
            table='application_rejected',
        ),
        migrations.AlterModelTable(
            name='assessment',
            table='assessment',
        ),
        migrations.AlterModelTable(
            name='enrollmentmanagement',
            table='enrollment_management',
        ),
        migrations.AlterModelTable(
            name='section',
            table='section',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
