# Generated by Django 5.1.6 on 2025-05-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0031_alter_announcement_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentform',
            name='enrollment_type',
            field=models.CharField(blank=True, choices=[('JHS', 'Junior High School'), ('SHS', 'Senior High School')], default='JHS', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st Semester'), ('2nd', '2nd Semester')], default='1st', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='strand',
            field=models.CharField(blank=True, choices=[('ABM', 'Accountancy, Business, and Management'), ('STEM', 'Science, Technology, Engineering, and Mathematics')], default='ABM', max_length=4, null=True),
        ),
    ]
