# Generated by Django 5.1.6 on 2025-05-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0032_alter_enrollmentform_enrollment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentform',
            name='enrollment_type',
            field=models.CharField(choices=[('JHS', 'Junior High School'), ('SHS', 'Senior High School')], default='JHS', max_length=3),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='with_lrn',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
