# Generated by Django 5.1.6 on 2025-05-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0034_documentlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlist',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
