# Generated by Django 5.1.6 on 2025-05-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0035_documentlist_is_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationapproved',
            old_name='application',
            new_name='enrollment',
        ),
        migrations.RenameField(
            model_name='applicationrejected',
            old_name='application',
            new_name='enrollment',
        ),
    ]
