# Generated by Django 5.1.6 on 2025-05-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0036_rename_application_applicationapproved_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentform',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
