# Generated by Django 5.1.6 on 2025-05-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0038_alter_enrollmentform_enrollment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentform',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_role',
        ),
    ]
