# Generated by Django 5.1.6 on 2025-05-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0039_remove_enrollmentform_user_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='application',
            new_name='application_approved',
        ),
    ]
