# Generated by Django 5.1.6 on 2025-05-15 21:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0040_rename_application_assessment_application_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('school_year', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('with_lrn', models.BooleanField(blank=True, null=True)),
                ('student_type', models.CharField(blank=True, max_length=255, null=True)),
                ('gen_avg', models.IntegerField()),
                ('new_avg', models.IntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=255, null=True)),
                ('psa_no', models.CharField(max_length=255)),
                ('lrn', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('extension_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('mother_tongue', models.CharField(max_length=255)),
                ('documents_submitted', models.TextField(blank=True, null=True)),
                ('early_reg', models.BooleanField(blank=True, null=True)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('enrollment_type', models.CharField(blank=True, choices=[('JHS', 'Junior High School'), ('SHS', 'Senior High School')], max_length=3, null=True)),
                ('semester', models.CharField(blank=True, choices=[('1st', '1st Semester'), ('2nd', '2nd Semester')], max_length=3, null=True)),
                ('strand', models.CharField(blank=True, choices=[('ABM', 'Accountancy, Business, and Management'), ('STEM', 'Science, Technology, Engineering, and Mathematics')], max_length=4, null=True)),
                ('student_status', models.CharField(choices=[('Enrolled', 'Enrolled'), ('Transferred', 'Transferred'), ('Dropped', 'Dropped')], default='Enrolled', max_length=50)),
                ('application_approved', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landingpage.applicationapproved')),
                ('assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landingpage.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_information',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
