# Generated by Django 5.1.6 on 2025-05-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0041_studentinformation_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinformation',
            name='new_avg',
        ),
    ]
