# Generated by Django 5.1.6 on 2025-05-15 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_remove_myuser_lrn_remove_myuser_psa_no_and_more'),
        ('landingpage', '0042_remove_studentinformation_new_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.teacherinformation'),
        ),
    ]
