# Generated by Django 5.1.6 on 2025-05-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0043_alter_section_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentmanagement',
            name='academic_year_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentmanagement',
            name='academic_year_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
