# Generated by Django 5.1.6 on 2025-05-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0044_enrollmentmanagement_academic_year_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformation',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
