# Generated by Django 5.1.6 on 2025-05-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0045_studentinformation_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinformation',
            old_name='is_completed',
            new_name='jhs_completed',
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='shs_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
