# Generated by Django 5.1.6 on 2025-05-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0046_rename_is_completed_studentinformation_jhs_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='strand',
            field=models.CharField(blank=True, choices=[('ABM', 'Accountancy, Business, and Management'), ('STEM', 'Science, Technology, Engineering, and Mathematics')], max_length=4, null=True),
        ),
    ]
