# Generated by Django 5.2.6 on 2025-09-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0047_section_strand'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformation',
            name='accept_term',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='literacy_level',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='numeracy_level',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='documentlist',
            name='document_name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='application_no',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='extension_name',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='first_name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='grade_level',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='last_name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='lrn',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='middle_name',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='mother_tongue',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='place_of_birth',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='psa_no',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='school_year',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='student_type',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='application_no',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='extension_name',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='first_name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='grade',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='last_name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='lrn',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='middle_name',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='mother_tongue',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='place_of_birth',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='psa_no',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='school_year',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='section',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='student_type',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
