# Generated by Django 5.2.6 on 2025-09-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0048_studentinformation_accept_term_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinformation',
            name='accept_term',
        ),
        migrations.AddField(
            model_name='enrollmentform',
            name='accept_term',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
