# Generated by Django 5.2.6 on 2025-09-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0049_remove_studentinformation_accept_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentform',
            name='accept_term',
            field=models.BooleanField(default=False),
        ),
    ]
