# Generated by Django 5.2.6 on 2025-09-21 15:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0050_alter_enrollmentform_accept_term'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=191)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.RemoveField(
            model_name='documentlist',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='documentlist',
            name='is_required',
        ),
        migrations.AddField(
            model_name='documentlist',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='landingpage.enrollmentform'),
        ),
        migrations.AddField(
            model_name='documentlist',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='application_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='extension_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='grade_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='lrn',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='mother_tongue',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='place_of_birth',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='psa_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='school_year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='student_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documentlist',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_lists', to='landingpage.document'),
        ),
    ]
