# Generated by Django 5.2.6 on 2025-09-28 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0051_document_remove_documentlist_document_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationRejected',
            new_name='ApplicationPending',
        ),
        migrations.RenameField(
            model_name='applicationpending',
            old_name='message_rejected',
            new_name='message_pending',
        ),
        migrations.AlterModelTable(
            name='applicationpending',
            table='application_pending',
        ),
    ]
