# Generated by Django 5.2.6 on 2025-10-01 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0052_rename_applicationrejected_applicationpending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlist',
            name='student_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='landingpage.studentinformation'),
        ),
    ]
