# Generated by Django 5.2.6 on 2025-10-11 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0054_alter_studentinformation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationapproved',
            name='is_assessed',
        ),
        migrations.AddField(
            model_name='applicationapproved',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applicationpending',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_assessed',
            field=models.BooleanField(default=False),
        ),
    ]
