# Generated by Django 5.2.6 on 2025-10-11 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0055_remove_applicationapproved_is_assessed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
