# Generated by Django 5.2.6 on 2025-10-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0056_assessment_created_at_alter_assessment_assessed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='literacy_level',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='literacy_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='numeracy_level',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='numeracy_result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
