# Generated by Django 5.2.6 on 2025-10-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0058_schoolyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='school_year_end',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='school_year_start',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
