# Generated by Django 5.2.6 on 2025-10-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0059_alter_schoolyear_school_year_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
