# Generated by Django 5.2.6 on 2025-10-13 09:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_admininformation_first_name_and_more'),
        ('landingpage', '0060_schoolyear_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentListHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.IntegerField(blank=True, null=True)),
                ('final_average', models.IntegerField(blank=True, null=True)),
                ('school_year', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.section')),
                ('student_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.studentinformation')),
                ('teacher_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.teacherinformation')),
            ],
            options={
                'db_table': 'student_list_history',
            },
        ),
    ]
