# Generated by Django 5.2.6 on 2025-10-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0061_studentlisthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed')], default='Active', max_length=10),
        ),
    ]
