# Generated by Django 5.2.6 on 2025-10-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0062_alter_section_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlisthistory',
            name='previous_final_average',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
