# Generated by Django 5.2.6 on 2025-10-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0064_faq_organizationchart'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationchart',
            name='department',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
