# Generated by Django 5.2.6 on 2025-10-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0065_organizationchart_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformation',
            name='enrollment_status',
            field=models.CharField(blank=True, choices=[('PASSED', 'PASSED'), ('FAILED', 'FAILED')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='submission_remarks',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
