# Generated by Django 5.2.6 on 2025-10-17 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0066_studentinformation_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentform',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
