# Generated by Django 5.2.6 on 2025-10-17 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0067_enrollmentform_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentform',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
