# Generated by Django 5.2.6 on 2025-10-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0068_alter_enrollmentform_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpending',
            name='is_reapproved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationpending',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
