# Generated by Django 5.2.6 on 2025-10-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0069_applicationpending_is_reapproved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='submission_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
