# Generated by Django 5.2.6 on 2025-10-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0070_alter_studentinformation_submission_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentform',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
