# Generated by Django 5.2.5 on 2025-10-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0071_alter_enrollmentform_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='application_no',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
