# Generated by Django 5.2.6 on 2025-10-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0072_alter_studentinformation_application_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpending',
            name='submission_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
