# Generated by Django 5.2.6 on 2025-10-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0073_applicationpending_submission_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentform',
            name='submission_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
