# Generated by Django 5.2.6 on 2025-10-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0074_enrollmentform_submission_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationpending',
            name='submission_remarks',
        ),
    ]
