# Generated by Django 5.1.6 on 2025-03-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="lrn",
            field=models.CharField(max_length=12, unique=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myuser",
            name="psa_no",
            field=models.CharField(max_length=20, unique=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myuser",
            name="first_name",
            field=models.CharField(max_length=30, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myuser",
            name="middle_name",
            field=models.CharField(max_length=30, blank=True, null=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="last_name",
            field=models.CharField(max_length=30, default=""),
            preserve_default=False,
        ),
    ]
