# Generated by Django 5.1.6 on 2025-03-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_auto"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
