# Generated by Django 5.1.6 on 2025-03-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_add_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="username",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
