# Generated by Django 5.1.6 on 2025-03-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_update_username_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='lrn',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='psa_no',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
