# Generated by Django 5.1.6 on 2025-03-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_myuser_first_name_alter_myuser_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
    ]
