# Generated by Django 5.1.6 on 2025-03-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_myuser_is_admin_alter_myuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
