# Generated by Django 5.1.6 on 2025-03-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_myuser_last_logout_myuser_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='lrn',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='psa_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
