# Generated by Django 5.1.6 on 2025-04-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_myuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='grade_level_teacher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
