# Generated by Django 5.1.6 on 2025-04-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_myuser_grade_level_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_role',
            field=models.CharField(choices=[('Student', 'Student'), ('Applicant', 'Applicant'), ('Administrator', 'Administrator'), ('Coordinator', 'Coordinator'), ('Teacher', 'Teacher')], default='Applicant', max_length=50),
        ),
    ]
