# Generated by Django 5.1.6 on 2025-05-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_myuser_user_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myuser',
            table='user',
        ),
    ]
