# Generated by Django 5.1.6 on 2025-05-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_remove_myuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='lrn',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='psa_no',
        ),
        migrations.AddField(
            model_name='applicantinformation',
            name='lrn',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='applicantinformation',
            name='psa_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
