# Generated by Django 5.1.6 on 2025-05-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_remove_myuser_lrn_remove_myuser_psa_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
