# Generated by Django 5.1.6 on 2025-05-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_myuser_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='jhs_submitted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='shs_submitted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
