# Generated by Django 5.2.6 on 2025-09-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_myuser_jhs_submitted_myuser_shs_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininformation',
            name='first_name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='admininformation',
            name='last_name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='admininformation',
            name='middle_name',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='admininformation',
            name='position',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='first_name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='last_name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='lrn',
            field=models.CharField(blank=True, max_length=191, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='middle_name',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='psa_no',
            field=models.CharField(blank=True, max_length=191, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coordinatorinformation',
            name='first_name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='coordinatorinformation',
            name='last_name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='coordinatorinformation',
            name='middle_name',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='coordinatorinformation',
            name='position',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='first_name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='grade_level',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='last_name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='middle_name',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='position',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
