from django.urls import path
from adminside.views import (
    AdminApplicationBulkApproveView,
    AdminApplicationBulkReApproveView,
    AdminApplicationReApproveView,
    AdminDashboardView,
    AdminApplicationView,
    AdminReportsView,
    BulkApproveProgressView,
    BulkReApproveProgressView,
    GetApplicationDataView,
    UpdateApplicationView,
    AllUserView,
    AdminUserView,
    CoordinatorUserView,
    GetDocumentDataView,
    AdminDeleteUserView,
    AddAdminUserView,
    AdminLogoutView,
    ManageAnnouncementView,
    ManageEnrollmentView,
    AdminApplicationActionView,
    AddAnnouncementView,
    UpdateAnnouncementView,
    DeleteAnnouncementView,
    TeacherUserView,
    StudentUserView,
    AddCoordinatorUserView,
    AddStudentUserView,
    AddTeacherUserView,
    AdminDashboardDataAPI,
    AdminApplicationApprovedView,
    AdminApplicationRejectedView,
    AdminActionUserView,
    ChangePasswordView,
    GetUserDataView,
    AdminEditStudentStatusView,
    AdminEditUserView
)

urlpatterns = [
    path("dashboard/", AdminDashboardView.as_view(), name="admin_dashboard"),
    path("application/", AdminApplicationView.as_view(), name="application"),
    path("reports/", AdminReportsView.as_view(), name="reports"),
    path(
        "get_application/<int:application_id>/",
        GetApplicationDataView.as_view(),
        name="get_application",
    ),
    path(
        "update_application/<int:application_id>/",
        UpdateApplicationView.as_view(),
        name="update_application",
    ),
    path("users/", AllUserView.as_view(), name="admin_all_users"),
    path(
        "get_documents/<int:application_id>/",
        GetDocumentDataView.as_view(),
        name="get_documents",
    ),
    path(
        "delete_user/<int:user_id>/", AdminDeleteUserView.as_view(), name="delete_user"
    ),
    path("admin-users/", AdminUserView.as_view(), name="admin_users"),
    path("add_admin/", AddAdminUserView.as_view(), name="add_admin_user"),
    path("logout/", AdminLogoutView.as_view(), name="admin_logout"),
    path(
        "manage-announcement/",
        ManageAnnouncementView.as_view(),
        name="manage_announcement",
    ),
    path("add-announcement/", AddAnnouncementView.as_view(), name="add_announcement"),
    path(
        "update-announcement/<int:announcement_id>/",
        UpdateAnnouncementView.as_view(),
        name="update_announcement",
    ),
    path(
        "delete-announcement/<int:announcement_id>/",
        DeleteAnnouncementView.as_view(),
        name="delete_announcement",
    ),
    path(
        "manage-enrollment/",
        ManageEnrollmentView.as_view(),
        name="manage_enrollment",
    ),
    path(
        "application_action/",
        AdminApplicationActionView.as_view(),
        name="application_action",
    ),
    path(
        "bulk_approve/",
        AdminApplicationBulkApproveView.as_view(),
        name="bulk_approve",
    ),
    path(
        "bulk_reapprove/",
        AdminApplicationBulkReApproveView.as_view(),
        name="bulk_reapprove",
    ),
    path('bulk-reapprove-progress/<str:batch_key>/', BulkReApproveProgressView.as_view(), name='bulk-reapprove-progress'),
    path('bulk-approve-progress/<str:batch_key>/', BulkApproveProgressView.as_view(), name='bulk-approve-progress'),
    path(
        "reapprove_action/",
        AdminApplicationReApproveView.as_view(),
        name="reapprove_action",
    ),
    path("coordinator-users/", CoordinatorUserView.as_view(), name="coordinator_users"),
    path(
        "add_coordinator/",
        AddCoordinatorUserView.as_view(),
        name="add_coordinator_user",
    ),
    path("teacher-users/", TeacherUserView.as_view(), name="teacher_users"),
    path("add_teacher/", AddTeacherUserView.as_view(), name="add_teacher_user"),
    path("student-users/", StudentUserView.as_view(), name="student_users"),
    path("add_student/", AddStudentUserView.as_view(), name="add_student_user"),
    path("dashboard-data/", AdminDashboardDataAPI.as_view(), name="dashboard_data"),
    path(
        "application_approved/",
        AdminApplicationApprovedView.as_view(),
        name="application_approved",
    ),
    path(
        "application_rejected/",
        AdminApplicationRejectedView.as_view(),
        name="application_rejected",
    ),
    path(
        "deactivate_user/<int:user_id>/",
        AdminActionUserView.as_view(),
        name="deactivate_user",
    ),
    path(
        "change_password/",
        ChangePasswordView.as_view(),
        name="change_password",
    ),
    path(
        "get_user_data/<int:user_id>/<str:user_role>/",
        GetUserDataView.as_view(),
        name="get_user_data",
    ),
    path(
        "edit_student_status/<int:student_id>/",
        AdminEditStudentStatusView.as_view(),
        name="admin_edit_student_status",
    ),
    path(
        "edit_user/<int:user_id>/<str:user_role>/",
        AdminEditUserView.as_view(),
        name="admin_edit_user",
    ),
]
